version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: smartqueue_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smartqueue
      POSTGRES_USER: smartqueue
      POSTGRES_PASSWORD: smartqueue
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: smartqueue_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: smartqueue_backend
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: smartqueue_backend.settings.dev
    volumes:
      - ./backend:/app
    # ports:
    #   - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  celery:
    build:
      context: ./backend
    container_name: smartqueue_celery
    restart: unless-stopped
    depends_on:
      - backend
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: smartqueue_backend.settings.dev
    volumes:
      - ./backend:/app
    command: celery -A smartqueue_backend worker -l info

  celery_beat:
    build:
      context: ./backend
    container_name: smartqueue_celery_beat
    restart: unless-stopped
    depends_on:
      - backend
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: smartqueue_backend.settings.dev
    volumes:
      - ./backend:/app
    command: celery -A smartqueue_backend beat -l info

  frontend:
    build:
      context: ./back_office
    container_name: smartqueue_frontend
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    volumes:
      - ./back_office:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: ""
    depends_on:
      - backend

  client_app:
    build:
      context: ./frontend
    container_name: smartqueue_client
    restart: unless-stopped
    # ports:
    #   - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: "https://5sursync.eu"
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: smartqueue_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/ssl
      - ./nginx/auth:/etc/nginx/auth
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    container_name: smartqueue_certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw

volumes:
  postgres_data:
